SPK_NAME = cli-util
SPK_VERS = 0.2
SPK_REV = 2
SPK_ICON = src/icon.png

DEPENDS = cross/screen cross/links cross/less cross/tree cross/file cross/iconv cross/pv

MAINTAINER = ish-west
DESCRIPTION = "Some command line utilities: screen, less, file, tree, links, iconv, pv"
DISPLAY_NAME = CLI Utilities
STARTABLE = no

HOMEPAGE = https://github.com/SynoCommunity/spksrc/wiki
LICENSE  = Each tool is licensed under it\'s respective license.

SPK_COMMANDS = bin/screen
SPK_COMMANDS += bin/links
SPK_COMMANDS += bin/less bin/lessecho bin/lesskey
SPK_COMMANDS += bin/tree
SPK_COMMANDS += bin/file
SPK_COMMANDS += bin/iconv
SPK_COMMANDS += bin/pv

include ../../mk/spksrc.spk.mk
